# Generated by Django 4.0.1 on 2022-05-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Account_Code', models.CharField(max_length=10)),
                ('Account_Name', models.CharField(max_length=50)),
                ('Account_Type', models.CharField(max_length=10)),
                ('Card_Type', models.CharField(max_length=10)),
                ('Card_Number', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('Remarks', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
