# Generated by Django 4.0.1 on 2022-05-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='Partnership',
            field=models.CharField(default='YellowCoin', max_length=100),
        ),
    ]
