# Generated by Django 4.0.1 on 2022-05-26 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useraccount_partnership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='Password',
        ),
    ]
